version: "3"

services:
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    ports:
      - 3000:3000

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend/src:/app/src
    ports:
      - 8000:3000
